// Level configuration — the single source of truth for maze layout, scoring,
// and train behavior. Adding level 6+ means adding an object here; the game
// engine reads this generically and never special-cases a level number.
//
// Maze legend (each row is a string, each character a cell):
//   '#'  wall (impassable)
//   '.'  track with a regular dot (10 pts)
//   'o'  track with a power dot (50 pts, triggers power mode) — placed at
//        runtime by the engine at the cells farthest from the player start,
//        not hardcoded here (see engine/collision.js choosePowerDotCells)
//   'P'  player start position (rendered as track underneath)
//   'C'  Canada Line train start
//   'E'  Expo Line train start
//   'M'  Millennium Line train start
//
// Every maze below was generated by carving walls into an open room while
// checking full connectivity after each carve (see tools/gen_maze.py in this
// repo), so every floor cell is guaranteed reachable from every other floor
// cell — there is no dead pocket a dot could get stranded in.
//
// Train behavior options:
//   'patrol'    — moves along a fixed loop, ignores player position
//   'chase'     — always steps toward the player's current cell
//   'intercept' — steps toward a cell a few tiles ahead of the player's
//                 current heading (cuts corners rather than tailing)

const LEVEL_1_MAZE = [
  '###########',
  '#..#...#..#',
  '#.#.....#.#',
  '#.........#',
  '#....#....#',
  '###.....###',
  '###.....###',
  '###P#.#.###',
  '#C###.###.#',
  '#.........#',
  '###########'
];

const LEVEL_2_MAZE = [
  '#############',
  '#####...#####',
  '#..##...##..#',
  '##...#.#P..##',
  '##.#.....#.##',
  '#.C.........#',
  '#..#..#..#..#',
  '##.#..#..#.##',
  '##.##...##.##',
  '###...#...###',
  '#....###...E#',
  '#...........#',
  '#############'
];

const LEVEL_3_MAZE = [
  '###############',
  '##P.#.#.#.#..##',
  '##..#.#.#.#..##',
  '##.#.......#.##',
  '#...E#...#....#',
  '##...##.##..M##',
  '#......#......#',
  '##.##.....##.##',
  '##...##.##...##',
  '#.##.##.##.##.#',
  '#.....#.#.....#',
  '#..#.#...#.#.C#',
  '##..##...##..##',
  '##....#.#....##',
  '###############'
];

const LEVEL_4_MAZE = [
  '###################',
  '##.###.......###.##',
  '#.................#',
  '#..#...#...#...#.M#',
  '#.##.#.#####.#.##.#',
  '##..#.P##.##..#..##',
  '#....#.##.##.#....#',
  '#.##...##.##...##.#',
  '#..#.#.##.##.#.#..#',
  '#.##..##...##..##.#',
  '#...#.#E....#.#...#',
  '#.#C.##..#..##..#.#',
  '#.#..#...#...#..#.#',
  '#.#.#..#...#..#.#.#',
  '###...###.###...###',
  '#.....##...##.....#',
  '###################'
];

const LEVEL_5_MAZE = [
  '#####################',
  '#.#.###..#.#.C###.#.#',
  '#.#...............#.#',
  '#.......##.##.......#',
  '###.###...#...###.###',
  '##..#.#.......#.#..##',
  '#...#.####.####.#E..#',
  '###.#.##.....##.#.###',
  '##....#.#####.#....##',
  '##.#.#...###M..#.#.##',
  '#.#..##..#.#..##..#.#',
  '#..#.P...#.#.....#..#',
  '#.#..#.#.#.#.#.#..#.#',
  '#...####.....####...#',
  '#.##.##..###..##.##.#',
  '###..###.#.#.###..###',
  '##.................##',
  '#..#.#.#.....#.#.#..#',
  '#####################'
];

export const LEVELS = [
  {
    id: 1,
    name: 'Waterfront',
    threshold: 300,
    lives: 3,
    maze: LEVEL_1_MAZE,
    powerDuration: 6000,
    trains: [{ line: 'canada', behavior: 'patrol', speed: 340 }]
  },
  {
    id: 2,
    name: 'Commercial–Broadway',
    threshold: 520,
    lives: 3,
    maze: LEVEL_2_MAZE,
    powerDuration: 6000,
    trains: [
      { line: 'canada', behavior: 'patrol', speed: 300 },
      { line: 'expo', behavior: 'chase', speed: 320 }
    ]
  },
  {
    id: 3,
    name: 'Metrotown',
    threshold: 840,
    lives: 3,
    maze: LEVEL_3_MAZE,
    powerDuration: 6000,
    trains: [
      { line: 'canada', behavior: 'chase', speed: 280 },
      { line: 'expo', behavior: 'intercept', speed: 300 },
      { line: 'millennium', behavior: 'patrol', speed: 300 }
    ]
  },
  {
    id: 4,
    name: 'Production Way',
    threshold: 1310,
    lives: 3,
    maze: LEVEL_4_MAZE,
    powerDuration: 5000,
    trains: [
      { line: 'canada', behavior: 'chase', speed: 250 },
      { line: 'expo', behavior: 'chase', speed: 260 },
      { line: 'millennium', behavior: 'intercept', speed: 260 }
    ]
  },
  {
    id: 5,
    name: 'King George',
    threshold: 1670,
    lives: 3,
    maze: LEVEL_5_MAZE,
    powerDuration: 4000,
    trains: [
      { line: 'canada', behavior: 'intercept', speed: 220 },
      { line: 'expo', behavior: 'chase', speed: 220 },
      { line: 'millennium', behavior: 'intercept', speed: 230 }
    ]
  }
];

export const DOT_SCORE = 10;
export const POWER_DOT_SCORE = 50;
export const TRAIN_CAPTURE_SCORE = 200;
export const POWER_DOT_COUNT = 4;

export function getLevelById(id) {
  return LEVELS.find((lvl) => lvl.id === id) ?? null;
}
